name: hrs_site
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  http:
  freezed_annotation: ^2.2.0
  # json_annotation: ^4.8.0
  dart_mappable: ^3.0.0-dev.2
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.0
  dart_mappable_builder: ^3.0.0-dev.2
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lints: ^2.0.0
